apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-simple
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/vimalpatel19/kubectl-simple/releases/download/v0.1.0/kubectl-simple_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-simple"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-simple"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/vimalpatel19/kubectl-simple/releases/download/v0.1.0/kubectl-simple_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-simple"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-simple"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/vimalpatel19/kubectl-simple/releases/download/v0.1.0/kubectl-simple_windows_amd64.zip
    sha256: ""
    files:
    - from: "/kubectl-simple.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-simple.exe"
  shortDescription: A new plugin
  homepage: https://github.com/vimalpatel19/kubectl-simple
  caveats: |
    Usage:
      $ kubectl kubectl-simple

    For additional options:
      $ kubectl kubectl-simple --help
      or https://github.com/vimalpatel19/kubectl-simple/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
